export const CHECK_ANSWERS = 'CHECK_ANSWERS';
export const FETCH_TASK_ERROR = 'FETCH_TASK_ERROR';
export const FETCH_TASK_REQUESTED = 'FETCH_TASK_REQUESTED';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const INITIALIZE_APPLICATION = 'INITIALIZE_APPLICATION';
export const SELECT_ANSWER_EVENT = 'SELECT_ANSWER_EVENT';
export const SELECT_ANSWER_COMPLETE = 'SELECT_ANSWER_COMPLETE';
